name: Backend TaskFlow Build & Logical Test

# When
on:
  push:
    paths:
      - 'apps/api/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'apps/api/**'
    branches: [ "main" ]

# What to do
jobs:
  build-and-test:
    # Operating System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Backend Dependencies
        working-directory: ./apps/api
        run: npm install

      - name: Run Backend Tests
        working-directory: ./apps/api
        run: npm test
